apiVersion: application-networking.k8s.aws/v1alpha1
kind: ServiceExport
metadata:
  name: multi-protocol-service
  annotations:
    application-networking.k8s.aws/federation: "amazon-vpc-lattice"
spec:
  exportedPorts:
  - port: 80
    routeType: HTTP
  - port: 8081
    routeType: GRPC
  - port: 443
    routeType: TLS
