version: "2"
linters:
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "ST1012:"
      - linters:
          - staticcheck
        text: "QF1003:"
      - linters:
          - staticcheck
        text: "QF1001:"
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
