// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice (interfaces: AccessLogSubscriptionManager)
//
// Generated by this command:
//
//	mockgen -destination access_log_subscription_manager_mock.go -package lattice github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice AccessLogSubscriptionManager
//

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessLogSubscriptionManager is a mock of AccessLogSubscriptionManager interface.
type MockAccessLogSubscriptionManager struct {
	ctrl     *gomock.Controller
	recorder *MockAccessLogSubscriptionManagerMockRecorder
	isgomock struct{}
}

// MockAccessLogSubscriptionManagerMockRecorder is the mock recorder for MockAccessLogSubscriptionManager.
type MockAccessLogSubscriptionManagerMockRecorder struct {
	mock *MockAccessLogSubscriptionManager
}

// NewMockAccessLogSubscriptionManager creates a new mock instance.
func NewMockAccessLogSubscriptionManager(ctrl *gomock.Controller) *MockAccessLogSubscriptionManager {
	mock := &MockAccessLogSubscriptionManager{ctrl: ctrl}
	mock.recorder = &MockAccessLogSubscriptionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessLogSubscriptionManager) EXPECT() *MockAccessLogSubscriptionManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccessLogSubscriptionManager) Create(ctx context.Context, accessLogSubscription *lattice.AccessLogSubscription) (*lattice.AccessLogSubscriptionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, accessLogSubscription)
	ret0, _ := ret[0].(*lattice.AccessLogSubscriptionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccessLogSubscriptionManagerMockRecorder) Create(ctx, accessLogSubscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccessLogSubscriptionManager)(nil).Create), ctx, accessLogSubscription)
}

// Delete mocks base method.
func (m *MockAccessLogSubscriptionManager) Delete(ctx context.Context, accessLogSubscriptionArn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, accessLogSubscriptionArn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessLogSubscriptionManagerMockRecorder) Delete(ctx, accessLogSubscriptionArn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessLogSubscriptionManager)(nil).Delete), ctx, accessLogSubscriptionArn)
}

// Update mocks base method.
func (m *MockAccessLogSubscriptionManager) Update(ctx context.Context, accessLogSubscription *lattice.AccessLogSubscription) (*lattice.AccessLogSubscriptionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, accessLogSubscription)
	ret0, _ := ret[0].(*lattice.AccessLogSubscriptionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccessLogSubscriptionManagerMockRecorder) Update(ctx, accessLogSubscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccessLogSubscriptionManager)(nil).Update), ctx, accessLogSubscription)
}
