package lattice

const (
	LATTICE_CREATE_IN_PROGRESS = "LATTICE_CREATE_IN_PROGRESS"
	LATTICE_DELETE_IN_PROGRESS = "LATTICE_DELETE_IN_PROGRESS"
	LATTICE_NOT_FOUND          = "LATTICE_NOT_FOUND"
	LATTICE_ALREADY_EXIST      = "LATTICE_ALREADY_EXIST"
	LATTICE_RETRY              = "LATTICE_RETRY"
)
