// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice (interfaces: ListenerManager)
//
// Generated by this command:
//
//	mockgen -destination listener_manager_mock.go -package lattice github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice ListenerManager
//

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	types "github.com/aws/aws-sdk-go-v2/service/vpclattice/types"
	gomock "go.uber.org/mock/gomock"
)

// MockListenerManager is a mock of ListenerManager interface.
type MockListenerManager struct {
	ctrl     *gomock.Controller
	recorder *MockListenerManagerMockRecorder
	isgomock struct{}
}

// MockListenerManagerMockRecorder is the mock recorder for MockListenerManager.
type MockListenerManagerMockRecorder struct {
	mock *MockListenerManager
}

// NewMockListenerManager creates a new mock instance.
func NewMockListenerManager(ctrl *gomock.Controller) *MockListenerManager {
	mock := &MockListenerManager{ctrl: ctrl}
	mock.recorder = &MockListenerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerManager) EXPECT() *MockListenerManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockListenerManager) Delete(ctx context.Context, modelListener *lattice.Listener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, modelListener)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockListenerManagerMockRecorder) Delete(ctx, modelListener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockListenerManager)(nil).Delete), ctx, modelListener)
}

// List mocks base method.
func (m *MockListenerManager) List(ctx context.Context, serviceID string) ([]*types.ListenerSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, serviceID)
	ret0, _ := ret[0].([]*types.ListenerSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListenerManagerMockRecorder) List(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListenerManager)(nil).List), ctx, serviceID)
}

// Upsert mocks base method.
func (m *MockListenerManager) Upsert(ctx context.Context, modelListener *lattice.Listener, modelSvc *lattice.Service) (lattice.ListenerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, modelListener, modelSvc)
	ret0, _ := ret[0].(lattice.ListenerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockListenerManagerMockRecorder) Upsert(ctx, modelListener, modelSvc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockListenerManager)(nil).Upsert), ctx, modelListener, modelSvc)
}
