// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/deploy/lattice/rule_manager.go

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	vpclattice "github.com/aws/aws-sdk-go/service/vpclattice"
	gomock "github.com/golang/mock/gomock"
)

// MockRuleManager is a mock of RuleManager interface.
type MockRuleManager struct {
	ctrl     *gomock.Controller
	recorder *MockRuleManagerMockRecorder
}

// MockRuleManagerMockRecorder is the mock recorder for MockRuleManager.
type MockRuleManagerMockRecorder struct {
	mock *MockRuleManager
}

// NewMockRuleManager creates a new mock instance.
func NewMockRuleManager(ctrl *gomock.Controller) *MockRuleManager {
	mock := &MockRuleManager{ctrl: ctrl}
	mock.recorder = &MockRuleManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleManager) EXPECT() *MockRuleManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRuleManager) Delete(ctx context.Context, ruleId, serviceId, listenerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ruleId, serviceId, listenerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleManagerMockRecorder) Delete(ctx, ruleId, serviceId, listenerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleManager)(nil).Delete), ctx, ruleId, serviceId, listenerId)
}

// Get mocks base method.
func (m *MockRuleManager) Get(ctx context.Context, serviceId, listenerId, ruleId string) (*vpclattice.GetRuleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, serviceId, listenerId, ruleId)
	ret0, _ := ret[0].(*vpclattice.GetRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRuleManagerMockRecorder) Get(ctx, serviceId, listenerId, ruleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRuleManager)(nil).Get), ctx, serviceId, listenerId, ruleId)
}

// List mocks base method.
func (m *MockRuleManager) List(ctx context.Context, serviceId, listenerId string) ([]*vpclattice.RuleSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, serviceId, listenerId)
	ret0, _ := ret[0].([]*vpclattice.RuleSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRuleManagerMockRecorder) List(ctx, serviceId, listenerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRuleManager)(nil).List), ctx, serviceId, listenerId)
}

// UpdatePriorities mocks base method.
func (m *MockRuleManager) UpdatePriorities(ctx context.Context, svcId, listenerId string, rules []*lattice.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriorities", ctx, svcId, listenerId, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriorities indicates an expected call of UpdatePriorities.
func (mr *MockRuleManagerMockRecorder) UpdatePriorities(ctx, svcId, listenerId, rules interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriorities", reflect.TypeOf((*MockRuleManager)(nil).UpdatePriorities), ctx, svcId, listenerId, rules)
}

// Upsert mocks base method.
func (m *MockRuleManager) Upsert(ctx context.Context, modelRule *lattice.Rule, modelListener *lattice.Listener, modelSvc *lattice.Service) (lattice.RuleStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, modelRule, modelListener, modelSvc)
	ret0, _ := ret[0].(lattice.RuleStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRuleManagerMockRecorder) Upsert(ctx, modelRule, modelListener, modelSvc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRuleManager)(nil).Upsert), ctx, modelRule, modelListener, modelSvc)
}
