// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice (interfaces: ServiceNetworkManager)
//
// Generated by this command:
//
//	mockgen -destination service_network_manager_mock.go -package lattice github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice ServiceNetworkManager
//

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	services "github.com/aws/aws-application-networking-k8s/pkg/aws/services"
	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceNetworkManager is a mock of ServiceNetworkManager interface.
type MockServiceNetworkManager struct {
	ctrl     *gomock.Controller
	recorder *MockServiceNetworkManagerMockRecorder
	isgomock struct{}
}

// MockServiceNetworkManagerMockRecorder is the mock recorder for MockServiceNetworkManager.
type MockServiceNetworkManagerMockRecorder struct {
	mock *MockServiceNetworkManager
}

// NewMockServiceNetworkManager creates a new mock instance.
func NewMockServiceNetworkManager(ctrl *gomock.Controller) *MockServiceNetworkManager {
	mock := &MockServiceNetworkManager{ctrl: ctrl}
	mock.recorder = &MockServiceNetworkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceNetworkManager) EXPECT() *MockServiceNetworkManagerMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockServiceNetworkManager) CreateOrUpdate(ctx context.Context, serviceNetwork *lattice.ServiceNetwork) (lattice.ServiceNetworkStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, serviceNetwork)
	ret0, _ := ret[0].(lattice.ServiceNetworkStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockServiceNetworkManagerMockRecorder) CreateOrUpdate(ctx, serviceNetwork any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockServiceNetworkManager)(nil).CreateOrUpdate), ctx, serviceNetwork)
}

// DeleteVpcAssociation mocks base method.
func (m *MockServiceNetworkManager) DeleteVpcAssociation(ctx context.Context, snName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVpcAssociation", ctx, snName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVpcAssociation indicates an expected call of DeleteVpcAssociation.
func (mr *MockServiceNetworkManagerMockRecorder) DeleteVpcAssociation(ctx, snName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVpcAssociation", reflect.TypeOf((*MockServiceNetworkManager)(nil).DeleteVpcAssociation), ctx, snName)
}

// UpsertVpcAssociation mocks base method.
func (m *MockServiceNetworkManager) UpsertVpcAssociation(ctx context.Context, snName string, sgIds []*string, additionalTags services.Tags) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertVpcAssociation", ctx, snName, sgIds, additionalTags)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertVpcAssociation indicates an expected call of UpsertVpcAssociation.
func (mr *MockServiceNetworkManagerMockRecorder) UpsertVpcAssociation(ctx, snName, sgIds, additionalTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVpcAssociation", reflect.TypeOf((*MockServiceNetworkManager)(nil).UpsertVpcAssociation), ctx, snName, sgIds, additionalTags)
}
