// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice (interfaces: TargetsManager)
//
// Generated by this command:
//
//	mockgen -destination targets_manager_mock.go -package lattice github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice TargetsManager
//

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	vpclattice "github.com/aws/aws-sdk-go/service/vpclattice"
	gomock "go.uber.org/mock/gomock"
)

// MockTargetsManager is a mock of TargetsManager interface.
type MockTargetsManager struct {
	ctrl     *gomock.Controller
	recorder *MockTargetsManagerMockRecorder
	isgomock struct{}
}

// MockTargetsManagerMockRecorder is the mock recorder for MockTargetsManager.
type MockTargetsManagerMockRecorder struct {
	mock *MockTargetsManager
}

// NewMockTargetsManager creates a new mock instance.
func NewMockTargetsManager(ctrl *gomock.Controller) *MockTargetsManager {
	mock := &MockTargetsManager{ctrl: ctrl}
	mock.recorder = &MockTargetsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetsManager) EXPECT() *MockTargetsManagerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTargetsManager) List(ctx context.Context, modelTg *lattice.TargetGroup) ([]*vpclattice.TargetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, modelTg)
	ret0, _ := ret[0].([]*vpclattice.TargetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTargetsManagerMockRecorder) List(ctx, modelTg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTargetsManager)(nil).List), ctx, modelTg)
}

// Update mocks base method.
func (m *MockTargetsManager) Update(ctx context.Context, modelTargets *lattice.Targets, modelTg *lattice.TargetGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, modelTargets, modelTg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTargetsManagerMockRecorder) Update(ctx, modelTargets, modelTg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTargetsManager)(nil).Update), ctx, modelTargets, modelTg)
}
