// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice (interfaces: TargetGroupManager)
//
// Generated by this command:
//
//	mockgen -destination target_group_manager_mock.go -package lattice github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice TargetGroupManager
//

// Package lattice is a generated GoMock package.
package lattice

import (
	context "context"
	reflect "reflect"

	core "github.com/aws/aws-application-networking-k8s/pkg/model/core"
	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	types "github.com/aws/aws-sdk-go-v2/service/vpclattice/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTargetGroupManager is a mock of TargetGroupManager interface.
type MockTargetGroupManager struct {
	ctrl     *gomock.Controller
	recorder *MockTargetGroupManagerMockRecorder
	isgomock struct{}
}

// MockTargetGroupManagerMockRecorder is the mock recorder for MockTargetGroupManager.
type MockTargetGroupManagerMockRecorder struct {
	mock *MockTargetGroupManager
}

// NewMockTargetGroupManager creates a new mock instance.
func NewMockTargetGroupManager(ctrl *gomock.Controller) *MockTargetGroupManager {
	mock := &MockTargetGroupManager{ctrl: ctrl}
	mock.recorder = &MockTargetGroupManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetGroupManager) EXPECT() *MockTargetGroupManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTargetGroupManager) Delete(ctx context.Context, modelTg *lattice.TargetGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, modelTg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTargetGroupManagerMockRecorder) Delete(ctx, modelTg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTargetGroupManager)(nil).Delete), ctx, modelTg)
}

// IsTargetGroupMatch mocks base method.
func (m *MockTargetGroupManager) IsTargetGroupMatch(ctx context.Context, modelTg *lattice.TargetGroup, latticeTg *types.TargetGroupSummary, latticeTags *lattice.TargetGroupTagFields) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTargetGroupMatch", ctx, modelTg, latticeTg, latticeTags)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTargetGroupMatch indicates an expected call of IsTargetGroupMatch.
func (mr *MockTargetGroupManagerMockRecorder) IsTargetGroupMatch(ctx, modelTg, latticeTg, latticeTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTargetGroupMatch", reflect.TypeOf((*MockTargetGroupManager)(nil).IsTargetGroupMatch), ctx, modelTg, latticeTg, latticeTags)
}

// List mocks base method.
func (m *MockTargetGroupManager) List(ctx context.Context) ([]tgListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]tgListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTargetGroupManagerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTargetGroupManager)(nil).List), ctx)
}

// ResolveRuleTgIds mocks base method.
func (m *MockTargetGroupManager) ResolveRuleTgIds(ctx context.Context, modelRuleAction *lattice.RuleAction, stack core.Stack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRuleTgIds", ctx, modelRuleAction, stack)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveRuleTgIds indicates an expected call of ResolveRuleTgIds.
func (mr *MockTargetGroupManagerMockRecorder) ResolveRuleTgIds(ctx, modelRuleAction, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRuleTgIds", reflect.TypeOf((*MockTargetGroupManager)(nil).ResolveRuleTgIds), ctx, modelRuleAction, stack)
}

// Upsert mocks base method.
func (m *MockTargetGroupManager) Upsert(ctx context.Context, modelTg *lattice.TargetGroup) (lattice.TargetGroupStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, modelTg)
	ret0, _ := ret[0].(lattice.TargetGroupStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTargetGroupManagerMockRecorder) Upsert(ctx, modelTg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTargetGroupManager)(nil).Upsert), ctx, modelTg)
}
