apiVersion: v1
kind: ConfigMap
metadata:
    name: env-config
data:
    awsRegion: {{ .Values.awsRegion | quote }}
    awsAccountId: {{ .Values.awsAccountId | quote }}
    clusterVpcId: {{ .Values.clusterVpcId | quote }}
