// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/k8s (interfaces: FinalizerManager)
//
// Generated by this command:
//
//	mockgen -destination finalizer_mock.go -package k8s github.com/aws/aws-application-networking-k8s/pkg/k8s FinalizerManager
//

// Package k8s is a generated GoMock package.
package k8s

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockFinalizerManager is a mock of FinalizerManager interface.
type MockFinalizerManager struct {
	ctrl     *gomock.Controller
	recorder *MockFinalizerManagerMockRecorder
	isgomock struct{}
}

// MockFinalizerManagerMockRecorder is the mock recorder for MockFinalizerManager.
type MockFinalizerManagerMockRecorder struct {
	mock *MockFinalizerManager
}

// NewMockFinalizerManager creates a new mock instance.
func NewMockFinalizerManager(ctrl *gomock.Controller) *MockFinalizerManager {
	mock := &MockFinalizerManager{ctrl: ctrl}
	mock.recorder = &MockFinalizerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinalizerManager) EXPECT() *MockFinalizerManagerMockRecorder {
	return m.recorder
}

// AddFinalizers mocks base method.
func (m *MockFinalizerManager) AddFinalizers(ctx context.Context, object client.Object, finalizers ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, object}
	for _, a := range finalizers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFinalizers", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFinalizers indicates an expected call of AddFinalizers.
func (mr *MockFinalizerManagerMockRecorder) AddFinalizers(ctx, object any, finalizers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, object}, finalizers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFinalizers", reflect.TypeOf((*MockFinalizerManager)(nil).AddFinalizers), varargs...)
}

// RemoveFinalizers mocks base method.
func (m *MockFinalizerManager) RemoveFinalizers(ctx context.Context, object client.Object, finalizers ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, object}
	for _, a := range finalizers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFinalizers", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFinalizers indicates an expected call of RemoveFinalizers.
func (mr *MockFinalizerManagerMockRecorder) RemoveFinalizers(ctx, object any, finalizers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, object}, finalizers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFinalizers", reflect.TypeOf((*MockFinalizerManager)(nil).RemoveFinalizers), varargs...)
}
