apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: gateway-api-controller
  name: gateway-api-controller-metrics-service
  namespace: aws-application-networking-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    control-plane: gateway-api-controller
