apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-export
  labels:
    app: cli-export
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cli-export
  template:
    metadata:
      labels:
        app: cli-export
    spec:
      containers:
      - name: cli-export
        image: public.ecr.aws/x2j8p8w7/http-server:latest
        env:
        - name: PodName
          value: "cli-export handler pod"


---
apiVersion: v1
kind: Service
metadata:
  name: cli-export
spec:
  selector:
    app: cli-export
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
