apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin-server
  labels:
    app: grpcbin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin-server
  template:
    metadata:
      labels:
        app: grpcbin-server
    spec:
      containers:
        - name: grpcbin-server
          image: moul/grpcbin:latest


---
apiVersion: v1
kind: Service
metadata:
  name: grpcbin-server
spec:
  selector:
    app: grpcbin-server
  ports:
    - name: over-http
      port: 19000
      targetPort: 9000
    - name: over-https
      port: 19001
      targetPort: 9001
