apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpcbin-grpc-route
spec:
  parentRefs:
    - name: my-hotel
      sectionName: https
  rules:
    - backendRefs:
        - name: grpcbin-server
          kind: Service
          port: 19000

