apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc
spec:
  parentRefs:
  - name: my-hotel
    sectionName: http
  rules:
  - backendRefs:
    - name: grpc-server
      kind: Service
      port: 50051
      weight: 10
    matches:
        - method:
            service: Greeter
