apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: inventory
  namespace: gw-infra-1
spec:
  parentRefs:
  - name: my-hotel
    namespace: gw-infra-1
    sectionName: http
  rules:
  - backendRefs:
    - name: inventory-v1
      namespace: gw-infra-1
      kind: Service
      port: 80
      weight: 10
