apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-ver2
  labels:
    app: parking-ver2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parking-ver2
  template:
    metadata:
      labels:
        app: parking-ver2
    spec:
      containers:
      - name: parking-ver2
        image: public.ecr.aws/x2j8p8w7/http-server:latest
        env:
        - name: PodName
          value: "parking-ver2 handler pod"


---
apiVersion: v1
kind: Service
metadata:
  name: parking-ver2
spec:
  selector:
    app: parking-ver2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
