apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: parking-ver2
  annotations:
    multicluster.x-k8s.io/aws-vpc: "your-vpc-id"
    multicluster.x-k8s.io/aws-eks-cluster-name: "lattice-eks-test-1"
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: TCP
