apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: parking-tls1
spec:
  hostnames:
  - tls-parking.my-test.com
  parentRefs:
  - name: my-hotel-feb28
    sectionName: tls
  rules:
  - backendRefs:
    - name: nginx
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /nginx
