apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-preprod
  labels:
    app: rate-preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-preprod
  template:
    metadata:
      labels:
        app: rate-preprod
    spec:
      containers:
      - name: aug24-rate-preprod
        image: public.ecr.aws/x2j8p8w7/http-server:latest
        env:
        - name: PodName
          value: "rate-preprod handler pod"


---
apiVersion: v1
kind: Service
metadata:
  name: rate-preprod
spec:
  selector:
    app: rate-preprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
