apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-canary
  labels:
    app: rate-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-canary
  template:
    metadata:
      labels:
        app: rate-canary
    spec:
      containers:
      - name: aug24-rate-canary
        image: public.ecr.aws/x2j8p8w7/http-server:latest
        env:
        - name: PodName
          value: "rate-canary handler pod"


---
apiVersion: v1
kind: Service
metadata:
  name: rate-canary
spec:
  selector:
    app: rate-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
