apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: second-account-gw1
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: http
    protocol: HTTP
    port: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-account-gw1-svc
  labels:
    app: second-account-gw1-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-account-gw1-svc
  template:
    metadata:
      labels:
        app: second-account-gw1-svc
    spec:
      containers:
        - name: second-account-gw1-svc-app
          image: public.ecr.aws/x2j8p8w7/http-server:latest
          env:
            - name: PodName
              value: "second-account-gw1-svc handler pod"


---
apiVersion: v1
kind: Service
metadata:
  name: second-account-gw1-svc
spec:
  selector:
    app: second-account-gw1-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090


---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: second-account-gw1-httproute
spec:
  parentRefs:
    - name:  second-account-gw1
      sectionName: http
  rules:
    - backendRefs:
        - name: second-account-gw1-svc
          kind: Service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
