apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
    name: test-policy
spec:
    targetRef:
        group: ""
        kind: Service
        name: inventory-ver1
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheck:
        enabled: true
        intervalSeconds: 10
