// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/aws/services (interfaces: ACM)
//
// Generated by this command:
//
//	mockgen -destination acm_mocks.go -package services github.com/aws/aws-application-networking-k8s/pkg/aws/services ACM
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	acm "github.com/aws/aws-sdk-go/service/acm"
	gomock "go.uber.org/mock/gomock"
)

// MockACM is a mock of ACM interface.
type MockACM struct {
	ctrl     *gomock.Controller
	recorder *MockACMMockRecorder
	isgomock struct{}
}

// MockACMMockRecorder is the mock recorder for MockACM.
type MockACMMockRecorder struct {
	mock *MockACM
}

// NewMockACM creates a new mock instance.
func NewMockACM(ctrl *gomock.Controller) *MockACM {
	mock := &MockACM{ctrl: ctrl}
	mock.recorder = &MockACMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockACM) EXPECT() *MockACMMockRecorder {
	return m.recorder
}

// ListCertificatesAsList mocks base method.
func (m *MockACM) ListCertificatesAsList(ctx context.Context, input *acm.ListCertificatesInput) ([]*acm.CertificateSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCertificatesAsList", ctx, input)
	ret0, _ := ret[0].([]*acm.CertificateSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCertificatesAsList indicates an expected call of ListCertificatesAsList.
func (mr *MockACMMockRecorder) ListCertificatesAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCertificatesAsList", reflect.TypeOf((*MockACM)(nil).ListCertificatesAsList), ctx, input)
}
