// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/aws/services (interfaces: Tagging)
//
// Generated by this command:
//
//	mockgen -destination tagging_mocks.go -package services github.com/aws/aws-application-networking-k8s/pkg/aws/services Tagging
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTagging is a mock of Tagging interface.
type MockTagging struct {
	ctrl     *gomock.Controller
	recorder *MockTaggingMockRecorder
	isgomock struct{}
}

// MockTaggingMockRecorder is the mock recorder for MockTagging.
type MockTaggingMockRecorder struct {
	mock *MockTagging
}

// NewMockTagging creates a new mock instance.
func NewMockTagging(ctrl *gomock.Controller) *MockTagging {
	mock := &MockTagging{ctrl: ctrl}
	mock.recorder = &MockTaggingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagging) EXPECT() *MockTaggingMockRecorder {
	return m.recorder
}

// FindResourcesByTags mocks base method.
func (m *MockTagging) FindResourcesByTags(ctx context.Context, resourceType ResourceType, tags Tags) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResourcesByTags", ctx, resourceType, tags)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResourcesByTags indicates an expected call of FindResourcesByTags.
func (mr *MockTaggingMockRecorder) FindResourcesByTags(ctx, resourceType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResourcesByTags", reflect.TypeOf((*MockTagging)(nil).FindResourcesByTags), ctx, resourceType, tags)
}

// GetTagsForArns mocks base method.
func (m *MockTagging) GetTagsForArns(ctx context.Context, arns []string) (map[string]Tags, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsForArns", ctx, arns)
	ret0, _ := ret[0].(map[string]Tags)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsForArns indicates an expected call of GetTagsForArns.
func (mr *MockTaggingMockRecorder) GetTagsForArns(ctx, arns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsForArns", reflect.TypeOf((*MockTagging)(nil).GetTagsForArns), ctx, arns)
}

// UpdateTags mocks base method.
func (m *MockTagging) UpdateTags(ctx context.Context, resourceArn string, additionalTags, awsManagedTags Tags) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTags", ctx, resourceArn, additionalTags, awsManagedTags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTags indicates an expected call of UpdateTags.
func (mr *MockTaggingMockRecorder) UpdateTags(ctx, resourceArn, additionalTags, awsManagedTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTags", reflect.TypeOf((*MockTagging)(nil).UpdateTags), ctx, resourceArn, additionalTags, awsManagedTags)
}
