// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/aws/services (interfaces: Lattice)
//
// Generated by this command:
//
//	mockgen -destination vpclattice_mocks.go -package services github.com/aws/aws-application-networking-k8s/pkg/aws/services Lattice
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	vpclattice "github.com/aws/aws-sdk-go-v2/service/vpclattice"
	types "github.com/aws/aws-sdk-go-v2/service/vpclattice/types"
	gomock "go.uber.org/mock/gomock"
)

// MockLattice is a mock of Lattice interface.
type MockLattice struct {
	ctrl     *gomock.Controller
	recorder *MockLatticeMockRecorder
	isgomock struct{}
}

// MockLatticeMockRecorder is the mock recorder for MockLattice.
type MockLatticeMockRecorder struct {
	mock *MockLattice
}

// NewMockLattice creates a new mock instance.
func NewMockLattice(ctrl *gomock.Controller) *MockLattice {
	mock := &MockLattice{ctrl: ctrl}
	mock.recorder = &MockLatticeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLattice) EXPECT() *MockLatticeMockRecorder {
	return m.recorder
}

// BatchUpdateRule mocks base method.
func (m *MockLattice) BatchUpdateRule(ctx context.Context, input *vpclattice.BatchUpdateRuleInput, optFns ...func(*vpclattice.Options)) (*vpclattice.BatchUpdateRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchUpdateRule", varargs...)
	ret0, _ := ret[0].(*vpclattice.BatchUpdateRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateRule indicates an expected call of BatchUpdateRule.
func (mr *MockLatticeMockRecorder) BatchUpdateRule(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateRule", reflect.TypeOf((*MockLattice)(nil).BatchUpdateRule), varargs...)
}

// CreateAccessLogSubscription mocks base method.
func (m *MockLattice) CreateAccessLogSubscription(ctx context.Context, input *vpclattice.CreateAccessLogSubscriptionInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateAccessLogSubscriptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccessLogSubscription", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateAccessLogSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessLogSubscription indicates an expected call of CreateAccessLogSubscription.
func (mr *MockLatticeMockRecorder) CreateAccessLogSubscription(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessLogSubscription", reflect.TypeOf((*MockLattice)(nil).CreateAccessLogSubscription), varargs...)
}

// CreateListener mocks base method.
func (m *MockLattice) CreateListener(ctx context.Context, input *vpclattice.CreateListenerInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateListenerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateListener", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateListener indicates an expected call of CreateListener.
func (mr *MockLatticeMockRecorder) CreateListener(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateListener", reflect.TypeOf((*MockLattice)(nil).CreateListener), varargs...)
}

// CreateRule mocks base method.
func (m *MockLattice) CreateRule(ctx context.Context, input *vpclattice.CreateRuleInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateRule", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockLatticeMockRecorder) CreateRule(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockLattice)(nil).CreateRule), varargs...)
}

// CreateService mocks base method.
func (m *MockLattice) CreateService(ctx context.Context, input *vpclattice.CreateServiceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateService", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockLatticeMockRecorder) CreateService(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockLattice)(nil).CreateService), varargs...)
}

// CreateServiceNetwork mocks base method.
func (m *MockLattice) CreateServiceNetwork(ctx context.Context, input *vpclattice.CreateServiceNetworkInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateServiceNetworkOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateServiceNetwork", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateServiceNetworkOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceNetwork indicates an expected call of CreateServiceNetwork.
func (mr *MockLatticeMockRecorder) CreateServiceNetwork(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceNetwork", reflect.TypeOf((*MockLattice)(nil).CreateServiceNetwork), varargs...)
}

// CreateServiceNetworkServiceAssociation mocks base method.
func (m *MockLattice) CreateServiceNetworkServiceAssociation(ctx context.Context, input *vpclattice.CreateServiceNetworkServiceAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateServiceNetworkServiceAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateServiceNetworkServiceAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateServiceNetworkServiceAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceNetworkServiceAssociation indicates an expected call of CreateServiceNetworkServiceAssociation.
func (mr *MockLatticeMockRecorder) CreateServiceNetworkServiceAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceNetworkServiceAssociation", reflect.TypeOf((*MockLattice)(nil).CreateServiceNetworkServiceAssociation), varargs...)
}

// CreateServiceNetworkVpcAssociation mocks base method.
func (m *MockLattice) CreateServiceNetworkVpcAssociation(ctx context.Context, input *vpclattice.CreateServiceNetworkVpcAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateServiceNetworkVpcAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateServiceNetworkVpcAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateServiceNetworkVpcAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceNetworkVpcAssociation indicates an expected call of CreateServiceNetworkVpcAssociation.
func (mr *MockLatticeMockRecorder) CreateServiceNetworkVpcAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceNetworkVpcAssociation", reflect.TypeOf((*MockLattice)(nil).CreateServiceNetworkVpcAssociation), varargs...)
}

// CreateTargetGroup mocks base method.
func (m *MockLattice) CreateTargetGroup(ctx context.Context, input *vpclattice.CreateTargetGroupInput, optFns ...func(*vpclattice.Options)) (*vpclattice.CreateTargetGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTargetGroup", varargs...)
	ret0, _ := ret[0].(*vpclattice.CreateTargetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTargetGroup indicates an expected call of CreateTargetGroup.
func (mr *MockLatticeMockRecorder) CreateTargetGroup(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTargetGroup", reflect.TypeOf((*MockLattice)(nil).CreateTargetGroup), varargs...)
}

// DeleteAccessLogSubscription mocks base method.
func (m *MockLattice) DeleteAccessLogSubscription(ctx context.Context, input *vpclattice.DeleteAccessLogSubscriptionInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteAccessLogSubscriptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccessLogSubscription", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteAccessLogSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessLogSubscription indicates an expected call of DeleteAccessLogSubscription.
func (mr *MockLatticeMockRecorder) DeleteAccessLogSubscription(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessLogSubscription", reflect.TypeOf((*MockLattice)(nil).DeleteAccessLogSubscription), varargs...)
}

// DeleteAuthPolicy mocks base method.
func (m *MockLattice) DeleteAuthPolicy(ctx context.Context, input *vpclattice.DeleteAuthPolicyInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteAuthPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAuthPolicy", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteAuthPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAuthPolicy indicates an expected call of DeleteAuthPolicy.
func (mr *MockLatticeMockRecorder) DeleteAuthPolicy(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthPolicy", reflect.TypeOf((*MockLattice)(nil).DeleteAuthPolicy), varargs...)
}

// DeleteListener mocks base method.
func (m *MockLattice) DeleteListener(ctx context.Context, input *vpclattice.DeleteListenerInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteListenerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteListener", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteListener indicates an expected call of DeleteListener.
func (mr *MockLatticeMockRecorder) DeleteListener(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListener", reflect.TypeOf((*MockLattice)(nil).DeleteListener), varargs...)
}

// DeleteRule mocks base method.
func (m *MockLattice) DeleteRule(ctx context.Context, input *vpclattice.DeleteRuleInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRule", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockLatticeMockRecorder) DeleteRule(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockLattice)(nil).DeleteRule), varargs...)
}

// DeleteService mocks base method.
func (m *MockLattice) DeleteService(ctx context.Context, input *vpclattice.DeleteServiceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteService", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockLatticeMockRecorder) DeleteService(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockLattice)(nil).DeleteService), varargs...)
}

// DeleteServiceNetwork mocks base method.
func (m *MockLattice) DeleteServiceNetwork(ctx context.Context, input *vpclattice.DeleteServiceNetworkInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteServiceNetworkOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteServiceNetwork", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteServiceNetworkOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServiceNetwork indicates an expected call of DeleteServiceNetwork.
func (mr *MockLatticeMockRecorder) DeleteServiceNetwork(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceNetwork", reflect.TypeOf((*MockLattice)(nil).DeleteServiceNetwork), varargs...)
}

// DeleteServiceNetworkServiceAssociation mocks base method.
func (m *MockLattice) DeleteServiceNetworkServiceAssociation(ctx context.Context, input *vpclattice.DeleteServiceNetworkServiceAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteServiceNetworkServiceAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteServiceNetworkServiceAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteServiceNetworkServiceAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServiceNetworkServiceAssociation indicates an expected call of DeleteServiceNetworkServiceAssociation.
func (mr *MockLatticeMockRecorder) DeleteServiceNetworkServiceAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceNetworkServiceAssociation", reflect.TypeOf((*MockLattice)(nil).DeleteServiceNetworkServiceAssociation), varargs...)
}

// DeleteServiceNetworkVpcAssociation mocks base method.
func (m *MockLattice) DeleteServiceNetworkVpcAssociation(ctx context.Context, input *vpclattice.DeleteServiceNetworkVpcAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteServiceNetworkVpcAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteServiceNetworkVpcAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteServiceNetworkVpcAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServiceNetworkVpcAssociation indicates an expected call of DeleteServiceNetworkVpcAssociation.
func (mr *MockLatticeMockRecorder) DeleteServiceNetworkVpcAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceNetworkVpcAssociation", reflect.TypeOf((*MockLattice)(nil).DeleteServiceNetworkVpcAssociation), varargs...)
}

// DeleteTargetGroup mocks base method.
func (m *MockLattice) DeleteTargetGroup(ctx context.Context, input *vpclattice.DeleteTargetGroupInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeleteTargetGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTargetGroup", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeleteTargetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTargetGroup indicates an expected call of DeleteTargetGroup.
func (mr *MockLatticeMockRecorder) DeleteTargetGroup(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTargetGroup", reflect.TypeOf((*MockLattice)(nil).DeleteTargetGroup), varargs...)
}

// DeregisterTargets mocks base method.
func (m *MockLattice) DeregisterTargets(ctx context.Context, input *vpclattice.DeregisterTargetsInput, optFns ...func(*vpclattice.Options)) (*vpclattice.DeregisterTargetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeregisterTargets", varargs...)
	ret0, _ := ret[0].(*vpclattice.DeregisterTargetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeregisterTargets indicates an expected call of DeregisterTargets.
func (mr *MockLatticeMockRecorder) DeregisterTargets(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeregisterTargets", reflect.TypeOf((*MockLattice)(nil).DeregisterTargets), varargs...)
}

// FindService mocks base method.
func (m *MockLattice) FindService(ctx context.Context, latticeServiceName string) (*types.ServiceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindService", ctx, latticeServiceName)
	ret0, _ := ret[0].(*types.ServiceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindService indicates an expected call of FindService.
func (mr *MockLatticeMockRecorder) FindService(ctx, latticeServiceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindService", reflect.TypeOf((*MockLattice)(nil).FindService), ctx, latticeServiceName)
}

// FindServiceNetwork mocks base method.
func (m *MockLattice) FindServiceNetwork(ctx context.Context, nameOrId string) (*ServiceNetworkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindServiceNetwork", ctx, nameOrId)
	ret0, _ := ret[0].(*ServiceNetworkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindServiceNetwork indicates an expected call of FindServiceNetwork.
func (mr *MockLatticeMockRecorder) FindServiceNetwork(ctx, nameOrId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindServiceNetwork", reflect.TypeOf((*MockLattice)(nil).FindServiceNetwork), ctx, nameOrId)
}

// GetAccessLogSubscription mocks base method.
func (m *MockLattice) GetAccessLogSubscription(ctx context.Context, input *vpclattice.GetAccessLogSubscriptionInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetAccessLogSubscriptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccessLogSubscription", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetAccessLogSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessLogSubscription indicates an expected call of GetAccessLogSubscription.
func (mr *MockLatticeMockRecorder) GetAccessLogSubscription(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessLogSubscription", reflect.TypeOf((*MockLattice)(nil).GetAccessLogSubscription), varargs...)
}

// GetAuthPolicy mocks base method.
func (m *MockLattice) GetAuthPolicy(ctx context.Context, input *vpclattice.GetAuthPolicyInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetAuthPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAuthPolicy", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetAuthPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthPolicy indicates an expected call of GetAuthPolicy.
func (mr *MockLatticeMockRecorder) GetAuthPolicy(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthPolicy", reflect.TypeOf((*MockLattice)(nil).GetAuthPolicy), varargs...)
}

// GetListener mocks base method.
func (m *MockLattice) GetListener(ctx context.Context, input *vpclattice.GetListenerInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetListenerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetListener", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListener indicates an expected call of GetListener.
func (mr *MockLatticeMockRecorder) GetListener(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListener", reflect.TypeOf((*MockLattice)(nil).GetListener), varargs...)
}

// GetRule mocks base method.
func (m *MockLattice) GetRule(ctx context.Context, input *vpclattice.GetRuleInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRule", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockLatticeMockRecorder) GetRule(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockLattice)(nil).GetRule), varargs...)
}

// GetRulesAsList mocks base method.
func (m *MockLattice) GetRulesAsList(ctx context.Context, input *vpclattice.ListRulesInput) ([]*vpclattice.GetRuleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesAsList", ctx, input)
	ret0, _ := ret[0].([]*vpclattice.GetRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesAsList indicates an expected call of GetRulesAsList.
func (mr *MockLatticeMockRecorder) GetRulesAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesAsList", reflect.TypeOf((*MockLattice)(nil).GetRulesAsList), ctx, input)
}

// GetService mocks base method.
func (m *MockLattice) GetService(ctx context.Context, input *vpclattice.GetServiceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetService", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockLatticeMockRecorder) GetService(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockLattice)(nil).GetService), varargs...)
}

// GetServiceNetwork mocks base method.
func (m *MockLattice) GetServiceNetwork(ctx context.Context, input *vpclattice.GetServiceNetworkInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetServiceNetworkOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceNetwork", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetServiceNetworkOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceNetwork indicates an expected call of GetServiceNetwork.
func (mr *MockLatticeMockRecorder) GetServiceNetwork(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceNetwork", reflect.TypeOf((*MockLattice)(nil).GetServiceNetwork), varargs...)
}

// GetServiceNetworkServiceAssociation mocks base method.
func (m *MockLattice) GetServiceNetworkServiceAssociation(ctx context.Context, input *vpclattice.GetServiceNetworkServiceAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetServiceNetworkServiceAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceNetworkServiceAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetServiceNetworkServiceAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceNetworkServiceAssociation indicates an expected call of GetServiceNetworkServiceAssociation.
func (mr *MockLatticeMockRecorder) GetServiceNetworkServiceAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceNetworkServiceAssociation", reflect.TypeOf((*MockLattice)(nil).GetServiceNetworkServiceAssociation), varargs...)
}

// GetServiceNetworkVpcAssociation mocks base method.
func (m *MockLattice) GetServiceNetworkVpcAssociation(ctx context.Context, input *vpclattice.GetServiceNetworkVpcAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetServiceNetworkVpcAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceNetworkVpcAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetServiceNetworkVpcAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceNetworkVpcAssociation indicates an expected call of GetServiceNetworkVpcAssociation.
func (mr *MockLatticeMockRecorder) GetServiceNetworkVpcAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceNetworkVpcAssociation", reflect.TypeOf((*MockLattice)(nil).GetServiceNetworkVpcAssociation), varargs...)
}

// GetTargetGroup mocks base method.
func (m *MockLattice) GetTargetGroup(ctx context.Context, input *vpclattice.GetTargetGroupInput, optFns ...func(*vpclattice.Options)) (*vpclattice.GetTargetGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTargetGroup", varargs...)
	ret0, _ := ret[0].(*vpclattice.GetTargetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetGroup indicates an expected call of GetTargetGroup.
func (mr *MockLatticeMockRecorder) GetTargetGroup(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetGroup", reflect.TypeOf((*MockLattice)(nil).GetTargetGroup), varargs...)
}

// ListAccessLogSubscriptions mocks base method.
func (m *MockLattice) ListAccessLogSubscriptions(ctx context.Context, input *vpclattice.ListAccessLogSubscriptionsInput, optFns ...func(*vpclattice.Options)) (*vpclattice.ListAccessLogSubscriptionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAccessLogSubscriptions", varargs...)
	ret0, _ := ret[0].(*vpclattice.ListAccessLogSubscriptionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessLogSubscriptions indicates an expected call of ListAccessLogSubscriptions.
func (mr *MockLatticeMockRecorder) ListAccessLogSubscriptions(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessLogSubscriptions", reflect.TypeOf((*MockLattice)(nil).ListAccessLogSubscriptions), varargs...)
}

// ListListeners mocks base method.
func (m *MockLattice) ListListeners(ctx context.Context, input *vpclattice.ListListenersInput, optFns ...func(*vpclattice.Options)) (*vpclattice.ListListenersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListListeners", varargs...)
	ret0, _ := ret[0].(*vpclattice.ListListenersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListListeners indicates an expected call of ListListeners.
func (mr *MockLatticeMockRecorder) ListListeners(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListeners", reflect.TypeOf((*MockLattice)(nil).ListListeners), varargs...)
}

// ListListenersAsList mocks base method.
func (m *MockLattice) ListListenersAsList(ctx context.Context, input *vpclattice.ListListenersInput) ([]types.ListenerSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListListenersAsList", ctx, input)
	ret0, _ := ret[0].([]types.ListenerSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListListenersAsList indicates an expected call of ListListenersAsList.
func (mr *MockLatticeMockRecorder) ListListenersAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListenersAsList", reflect.TypeOf((*MockLattice)(nil).ListListenersAsList), ctx, input)
}

// ListRulesAsList mocks base method.
func (m *MockLattice) ListRulesAsList(ctx context.Context, input *vpclattice.ListRulesInput) ([]types.RuleSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRulesAsList", ctx, input)
	ret0, _ := ret[0].([]types.RuleSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRulesAsList indicates an expected call of ListRulesAsList.
func (mr *MockLatticeMockRecorder) ListRulesAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRulesAsList", reflect.TypeOf((*MockLattice)(nil).ListRulesAsList), ctx, input)
}

// ListServiceNetworkServiceAssociationsAsList mocks base method.
func (m *MockLattice) ListServiceNetworkServiceAssociationsAsList(ctx context.Context, input *vpclattice.ListServiceNetworkServiceAssociationsInput) ([]types.ServiceNetworkServiceAssociationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceNetworkServiceAssociationsAsList", ctx, input)
	ret0, _ := ret[0].([]types.ServiceNetworkServiceAssociationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceNetworkServiceAssociationsAsList indicates an expected call of ListServiceNetworkServiceAssociationsAsList.
func (mr *MockLatticeMockRecorder) ListServiceNetworkServiceAssociationsAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceNetworkServiceAssociationsAsList", reflect.TypeOf((*MockLattice)(nil).ListServiceNetworkServiceAssociationsAsList), ctx, input)
}

// ListServiceNetworkVpcAssociationsAsList mocks base method.
func (m *MockLattice) ListServiceNetworkVpcAssociationsAsList(ctx context.Context, input *vpclattice.ListServiceNetworkVpcAssociationsInput) ([]types.ServiceNetworkVpcAssociationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceNetworkVpcAssociationsAsList", ctx, input)
	ret0, _ := ret[0].([]types.ServiceNetworkVpcAssociationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceNetworkVpcAssociationsAsList indicates an expected call of ListServiceNetworkVpcAssociationsAsList.
func (mr *MockLatticeMockRecorder) ListServiceNetworkVpcAssociationsAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceNetworkVpcAssociationsAsList", reflect.TypeOf((*MockLattice)(nil).ListServiceNetworkVpcAssociationsAsList), ctx, input)
}

// ListServiceNetworksAsList mocks base method.
func (m *MockLattice) ListServiceNetworksAsList(ctx context.Context, input *vpclattice.ListServiceNetworksInput) ([]types.ServiceNetworkSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceNetworksAsList", ctx, input)
	ret0, _ := ret[0].([]types.ServiceNetworkSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceNetworksAsList indicates an expected call of ListServiceNetworksAsList.
func (mr *MockLatticeMockRecorder) ListServiceNetworksAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceNetworksAsList", reflect.TypeOf((*MockLattice)(nil).ListServiceNetworksAsList), ctx, input)
}

// ListServicesAsList mocks base method.
func (m *MockLattice) ListServicesAsList(ctx context.Context, input *vpclattice.ListServicesInput) ([]types.ServiceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesAsList", ctx, input)
	ret0, _ := ret[0].([]types.ServiceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesAsList indicates an expected call of ListServicesAsList.
func (mr *MockLatticeMockRecorder) ListServicesAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesAsList", reflect.TypeOf((*MockLattice)(nil).ListServicesAsList), ctx, input)
}

// ListTagsForResource mocks base method.
func (m *MockLattice) ListTagsForResource(ctx context.Context, input *vpclattice.ListTagsForResourceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.ListTagsForResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTagsForResource", varargs...)
	ret0, _ := ret[0].(*vpclattice.ListTagsForResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForResource indicates an expected call of ListTagsForResource.
func (mr *MockLatticeMockRecorder) ListTagsForResource(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResource", reflect.TypeOf((*MockLattice)(nil).ListTagsForResource), varargs...)
}

// ListTargetGroupsAsList mocks base method.
func (m *MockLattice) ListTargetGroupsAsList(ctx context.Context, input *vpclattice.ListTargetGroupsInput) ([]types.TargetGroupSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTargetGroupsAsList", ctx, input)
	ret0, _ := ret[0].([]types.TargetGroupSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTargetGroupsAsList indicates an expected call of ListTargetGroupsAsList.
func (mr *MockLatticeMockRecorder) ListTargetGroupsAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTargetGroupsAsList", reflect.TypeOf((*MockLattice)(nil).ListTargetGroupsAsList), ctx, input)
}

// ListTargetsAsList mocks base method.
func (m *MockLattice) ListTargetsAsList(ctx context.Context, input *vpclattice.ListTargetsInput) ([]types.TargetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTargetsAsList", ctx, input)
	ret0, _ := ret[0].([]types.TargetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTargetsAsList indicates an expected call of ListTargetsAsList.
func (mr *MockLatticeMockRecorder) ListTargetsAsList(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTargetsAsList", reflect.TypeOf((*MockLattice)(nil).ListTargetsAsList), ctx, input)
}

// PutAuthPolicy mocks base method.
func (m *MockLattice) PutAuthPolicy(ctx context.Context, input *vpclattice.PutAuthPolicyInput, optFns ...func(*vpclattice.Options)) (*vpclattice.PutAuthPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutAuthPolicy", varargs...)
	ret0, _ := ret[0].(*vpclattice.PutAuthPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutAuthPolicy indicates an expected call of PutAuthPolicy.
func (mr *MockLatticeMockRecorder) PutAuthPolicy(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAuthPolicy", reflect.TypeOf((*MockLattice)(nil).PutAuthPolicy), varargs...)
}

// RegisterTargets mocks base method.
func (m *MockLattice) RegisterTargets(ctx context.Context, input *vpclattice.RegisterTargetsInput, optFns ...func(*vpclattice.Options)) (*vpclattice.RegisterTargetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterTargets", varargs...)
	ret0, _ := ret[0].(*vpclattice.RegisterTargetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterTargets indicates an expected call of RegisterTargets.
func (mr *MockLatticeMockRecorder) RegisterTargets(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTargets", reflect.TypeOf((*MockLattice)(nil).RegisterTargets), varargs...)
}

// TagResource mocks base method.
func (m *MockLattice) TagResource(ctx context.Context, input *vpclattice.TagResourceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.TagResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TagResource", varargs...)
	ret0, _ := ret[0].(*vpclattice.TagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResource indicates an expected call of TagResource.
func (mr *MockLatticeMockRecorder) TagResource(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResource", reflect.TypeOf((*MockLattice)(nil).TagResource), varargs...)
}

// UntagResource mocks base method.
func (m *MockLattice) UntagResource(ctx context.Context, input *vpclattice.UntagResourceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UntagResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UntagResource", varargs...)
	ret0, _ := ret[0].(*vpclattice.UntagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UntagResource indicates an expected call of UntagResource.
func (mr *MockLatticeMockRecorder) UntagResource(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagResource", reflect.TypeOf((*MockLattice)(nil).UntagResource), varargs...)
}

// UpdateAccessLogSubscription mocks base method.
func (m *MockLattice) UpdateAccessLogSubscription(ctx context.Context, input *vpclattice.UpdateAccessLogSubscriptionInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateAccessLogSubscriptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateAccessLogSubscription", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateAccessLogSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessLogSubscription indicates an expected call of UpdateAccessLogSubscription.
func (mr *MockLatticeMockRecorder) UpdateAccessLogSubscription(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessLogSubscription", reflect.TypeOf((*MockLattice)(nil).UpdateAccessLogSubscription), varargs...)
}

// UpdateListener mocks base method.
func (m *MockLattice) UpdateListener(ctx context.Context, input *vpclattice.UpdateListenerInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateListenerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateListener", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateListener indicates an expected call of UpdateListener.
func (mr *MockLatticeMockRecorder) UpdateListener(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateListener", reflect.TypeOf((*MockLattice)(nil).UpdateListener), varargs...)
}

// UpdateRule mocks base method.
func (m *MockLattice) UpdateRule(ctx context.Context, input *vpclattice.UpdateRuleInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRule", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockLatticeMockRecorder) UpdateRule(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockLattice)(nil).UpdateRule), varargs...)
}

// UpdateService mocks base method.
func (m *MockLattice) UpdateService(ctx context.Context, input *vpclattice.UpdateServiceInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateService", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockLatticeMockRecorder) UpdateService(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockLattice)(nil).UpdateService), varargs...)
}

// UpdateServiceNetwork mocks base method.
func (m *MockLattice) UpdateServiceNetwork(ctx context.Context, input *vpclattice.UpdateServiceNetworkInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateServiceNetworkOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateServiceNetwork", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateServiceNetworkOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceNetwork indicates an expected call of UpdateServiceNetwork.
func (mr *MockLatticeMockRecorder) UpdateServiceNetwork(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceNetwork", reflect.TypeOf((*MockLattice)(nil).UpdateServiceNetwork), varargs...)
}

// UpdateServiceNetworkVpcAssociation mocks base method.
func (m *MockLattice) UpdateServiceNetworkVpcAssociation(ctx context.Context, input *vpclattice.UpdateServiceNetworkVpcAssociationInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateServiceNetworkVpcAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateServiceNetworkVpcAssociation", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateServiceNetworkVpcAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceNetworkVpcAssociation indicates an expected call of UpdateServiceNetworkVpcAssociation.
func (mr *MockLatticeMockRecorder) UpdateServiceNetworkVpcAssociation(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceNetworkVpcAssociation", reflect.TypeOf((*MockLattice)(nil).UpdateServiceNetworkVpcAssociation), varargs...)
}

// UpdateTargetGroup mocks base method.
func (m *MockLattice) UpdateTargetGroup(ctx context.Context, input *vpclattice.UpdateTargetGroupInput, optFns ...func(*vpclattice.Options)) (*vpclattice.UpdateTargetGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTargetGroup", varargs...)
	ret0, _ := ret[0].(*vpclattice.UpdateTargetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTargetGroup indicates an expected call of UpdateTargetGroup.
func (mr *MockLatticeMockRecorder) UpdateTargetGroup(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTargetGroup", reflect.TypeOf((*MockLattice)(nil).UpdateTargetGroup), varargs...)
}
