// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-application-networking-k8s/pkg/aws (interfaces: Cloud)
//
// Generated by this command:
//
//	mockgen -destination cloud_mocks.go -package aws github.com/aws/aws-application-networking-k8s/pkg/aws Cloud
//

// Package aws is a generated GoMock package.
package aws

import (
	context "context"
	reflect "reflect"

	services "github.com/aws/aws-application-networking-k8s/pkg/aws/services"
	gomock "go.uber.org/mock/gomock"
)

// MockCloud is a mock of Cloud interface.
type MockCloud struct {
	ctrl     *gomock.Controller
	recorder *MockCloudMockRecorder
	isgomock struct{}
}

// MockCloudMockRecorder is the mock recorder for MockCloud.
type MockCloudMockRecorder struct {
	mock *MockCloud
}

// NewMockCloud creates a new mock instance.
func NewMockCloud(ctrl *gomock.Controller) *MockCloud {
	mock := &MockCloud{ctrl: ctrl}
	mock.recorder = &MockCloudMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloud) EXPECT() *MockCloudMockRecorder {
	return m.recorder
}

// ACM mocks base method.
func (m *MockCloud) ACM() services.ACM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ACM")
	ret0, _ := ret[0].(services.ACM)
	return ret0
}

// ACM indicates an expected call of ACM.
func (mr *MockCloudMockRecorder) ACM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ACM", reflect.TypeOf((*MockCloud)(nil).ACM))
}

// Config mocks base method.
func (m *MockCloud) Config() CloudConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(CloudConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockCloudMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockCloud)(nil).Config))
}

// DefaultTags mocks base method.
func (m *MockCloud) DefaultTags() services.Tags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultTags")
	ret0, _ := ret[0].(services.Tags)
	return ret0
}

// DefaultTags indicates an expected call of DefaultTags.
func (mr *MockCloudMockRecorder) DefaultTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultTags", reflect.TypeOf((*MockCloud)(nil).DefaultTags))
}

// DefaultTagsMergedWith mocks base method.
func (m *MockCloud) DefaultTagsMergedWith(arg0 services.Tags) services.Tags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultTagsMergedWith", arg0)
	ret0, _ := ret[0].(services.Tags)
	return ret0
}

// DefaultTagsMergedWith indicates an expected call of DefaultTagsMergedWith.
func (mr *MockCloudMockRecorder) DefaultTagsMergedWith(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultTagsMergedWith", reflect.TypeOf((*MockCloud)(nil).DefaultTagsMergedWith), arg0)
}

// GetManagedByFromTags mocks base method.
func (m *MockCloud) GetManagedByFromTags(tags services.Tags) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagedByFromTags", tags)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetManagedByFromTags indicates an expected call of GetManagedByFromTags.
func (mr *MockCloudMockRecorder) GetManagedByFromTags(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedByFromTags", reflect.TypeOf((*MockCloud)(nil).GetManagedByFromTags), tags)
}

// IsArnManaged mocks base method.
func (m *MockCloud) IsArnManaged(ctx context.Context, arn string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsArnManaged", ctx, arn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsArnManaged indicates an expected call of IsArnManaged.
func (mr *MockCloudMockRecorder) IsArnManaged(ctx, arn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsArnManaged", reflect.TypeOf((*MockCloud)(nil).IsArnManaged), ctx, arn)
}

// Lattice mocks base method.
func (m *MockCloud) Lattice() services.Lattice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lattice")
	ret0, _ := ret[0].(services.Lattice)
	return ret0
}

// Lattice indicates an expected call of Lattice.
func (mr *MockCloudMockRecorder) Lattice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lattice", reflect.TypeOf((*MockCloud)(nil).Lattice))
}

// MergeTags mocks base method.
func (m *MockCloud) MergeTags(baseTags, additionalTags services.Tags) services.Tags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeTags", baseTags, additionalTags)
	ret0, _ := ret[0].(services.Tags)
	return ret0
}

// MergeTags indicates an expected call of MergeTags.
func (mr *MockCloudMockRecorder) MergeTags(baseTags, additionalTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeTags", reflect.TypeOf((*MockCloud)(nil).MergeTags), baseTags, additionalTags)
}

// Tagging mocks base method.
func (m *MockCloud) Tagging() services.Tagging {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tagging")
	ret0, _ := ret[0].(services.Tagging)
	return ret0
}

// Tagging indicates an expected call of Tagging.
func (mr *MockCloudMockRecorder) Tagging() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tagging", reflect.TypeOf((*MockCloud)(nil).Tagging))
}

// TryOwn mocks base method.
func (m *MockCloud) TryOwn(ctx context.Context, arn string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryOwn", ctx, arn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryOwn indicates an expected call of TryOwn.
func (mr *MockCloudMockRecorder) TryOwn(ctx, arn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryOwn", reflect.TypeOf((*MockCloud)(nil).TryOwn), ctx, arn)
}

// TryOwnFromTags mocks base method.
func (m *MockCloud) TryOwnFromTags(ctx context.Context, arn string, tags services.Tags) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryOwnFromTags", ctx, arn, tags)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryOwnFromTags indicates an expected call of TryOwnFromTags.
func (mr *MockCloudMockRecorder) TryOwnFromTags(ctx, arn, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryOwnFromTags", reflect.TypeOf((*MockCloud)(nil).TryOwnFromTags), ctx, arn, tags)
}
