// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/deploy/externaldns/dnsendpoint_manager.go

// Package externaldns is a generated GoMock package.
package externaldns

import (
	context "context"
	reflect "reflect"

	lattice "github.com/aws/aws-application-networking-k8s/pkg/model/lattice"
	gomock "github.com/golang/mock/gomock"
)

// MockDnsEndpointManager is a mock of DnsEndpointManager interface.
type MockDnsEndpointManager struct {
	ctrl     *gomock.Controller
	recorder *MockDnsEndpointManagerMockRecorder
}

// MockDnsEndpointManagerMockRecorder is the mock recorder for MockDnsEndpointManager.
type MockDnsEndpointManagerMockRecorder struct {
	mock *MockDnsEndpointManager
}

// NewMockDnsEndpointManager creates a new mock instance.
func NewMockDnsEndpointManager(ctrl *gomock.Controller) *MockDnsEndpointManager {
	mock := &MockDnsEndpointManager{ctrl: ctrl}
	mock.recorder = &MockDnsEndpointManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsEndpointManager) EXPECT() *MockDnsEndpointManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDnsEndpointManager) Create(ctx context.Context, service *lattice.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDnsEndpointManagerMockRecorder) Create(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDnsEndpointManager)(nil).Create), ctx, service)
}
