name: presubmit
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  presubmit:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.20.x", "1.21.x", "1.22.x", "1.23.x", "1.24.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v3
    - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19 # Reenable this once we move the module to 1.19 ${{ env.GO_VERSION }}
        check-latest: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
          ~/.kubebuilder/bin
        key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
    - run: make toolchain
    - run: make presubmit
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
